name: Build, Bump Version, and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: "https://registry.npmjs.org"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: 安装依赖
        run: |
          pnpm install

      - name: 编译
        run: pnpm build

      - name: 删除 js文件夹下 .d.ts 文件
        run: find js -name "*.d.ts" -type f -delete

      - name: 设置git用户名和邮箱
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 部署 js 到 build 分支（自动覆盖）
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./js/
          publish_branch: build # 目标分支为 build
          force_orphan: true # 强制覆盖，忽略历史

      - name: 打包
        run: |
          zip -r build.zip js

      - name: 上传 build.zip
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: build.zip

      - name: 更新版本号
        uses: google-github-actions/release-please-action@v3
        id: release_please
        with:
          release-type: node
          package-name: "karin-plugin-jacksixth-mycode"

      - name: 上传 release
        if: ${{ steps.release_please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release_please.outputs.tag_name }} build.zip
