name: Build, Bump Version, and Commit

on:
  push:
    branches:
      - main
  workflow_dispatch: # 允许手动触发
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 安装node
        uses: actions/setup-node@v4
        with:
          node-version: 21
          registry-url: "https://registry.npmjs.org"

      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.7.1

      - name: 安装依赖
        run: |
          pnpm install

      - name: 编译
        run: pnpm build

      - name: 设置git用户名和邮箱
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 清理并提交到 build 分支
        run: |
          rm -rf node_modules

          # 删除除 .js 外的文件
          cd js && find . -type f ! -name "*.js" -delete && cd ..

          # 创建或切换到 build 分支
          git checkout -b build || git checkout build

          # 清理已有的文件
          git reset
          git ls-files | xargs rm -f

          # 复制 js 和 readme.md 到根目录
          cp -r js/* ./
          cp -r readme.md ./

          # 添加、提交并推送到远程 build 分支
          git add .
          git commit -m "更新 build 分支"
          git push -f origin build
          git checkout main
          
      - name: 打包
        run: |
          zip -r build.zip js readme.md

      - name: 上传 build.zip
        uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: build.zip

      - name: 更新版本号
        uses: google-github-actions/release-please-action@v3
        id: release_please
        with:
          release-type: node
          package-name: "karin-plugin-jacksixth-app"

      - name: 上传 release
        if: ${{ steps.release_please.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release_please.outputs.tag_name }} build.zip
